apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  selector:
    matchLabels:
      app: backend
      tier: backend
      track: stable
  replicas: 2
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        track: stable
    spec:
      containers:
        - name: backend
          image: "281568417064.dkr.ecr.us-east-1.amazonaws.com/ecr-poc-backend:latest"
          ports:
            - name: http
              containerPort: 5000