apiVersion: v1
kind: Service
metadata:
  name: hello-ilb
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"  
spec:
  type: LoadBalancer
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 5000
    targetPort: http